Needle.create(size: 'US 0 (2.0 mm)')
Needle.create(size: 'US 1 (2.25 mm)')
Needle.create(size: 'US 1 1/2 (2.5 mm)')
Needle.create(size: 'US 2 (2.75 mm)')
Needle.create(size: 'US 2 1/2 (3.0 mm)')
Needle.create(size: 'US 3 (3.25 mm)')
Needle.create(size: 'US 4 (3.5 mm)')
Needle.create(size: 'US 5 (3.75 mm)')
Needle.create(size: 'US 6 (4.0 mm)')
Needle.create(size: 'US 7 (4.5 mm)')
Needle.create(size: 'US 8 (5.0 mm)')
Needle.create(size: 'US 9 (5.5 mm)')
Needle.create(size: 'US 10 (6.0 mm)')
Needle.create(size: 'US 10 1/2 (6.5 mm)')
Needle.create(size: '7 mm')
Needle.create(size: 'US 11 (8.0 mm)')
Needle.create(size: 'US 13 (9.0 mm)')
Needle.create(size: 'US 15 (10.0 mm)')

YarnWeight.create(weight: 'Lace', yardage_factor: 1.6)
YarnWeight.create(weight: 'Light Fingering', yardage_factor: 1.4)
YarnWeight.create(weight: 'Fingering', yardage_factor: 1.3)
YarnWeight.create(weight: 'Sport', yardage_factor: 1.2)
YarnWeight.create(weight: 'DK', yardage_factor: 1.1)
YarnWeight.create(weight: 'Worsted', yardage_factor: 1)
YarnWeight.create(weight: 'Aran', yardage_factor: 0.9)
YarnWeight.create(weight: 'Bulky', yardage_factor: 0.7)
YarnWeight.create(weight: 'Super Bulky', yardage_factor: 0.4)

Garment.create(category: 'Hat')
Garment.create(category: 'Shawl (Triangle)')

Yarn.create(brand: 'Malabrigo', color: 'Azul', yarn_weight_id: 7, yards: 200)
